[package]
name = "sonido"
version = "1.7.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
directories = "6.0.0"
lofty = "0.22.4"
ratatui = "0.29.0"
rodio = "0.20.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.23"
walkdir = "2.5.0"
