[config]
toggle_playback = "space"
toggle_repeat = "r"
seek_backward = "left"
seek_forward = "right"
seek_step = 5
previous_track = "up"
next_track = "down"
hide_track = "h"
reload_config = "c"
quit = "q"
show_app_title = false
show_playlist_title = false
show_playlist_scrollbar = false
show_metadata_title = false
show_metadata_panel = false
show_progress_title = false
app_title_format = ""
playlist_title_format = ""
metadata_title_format = ""
progress_title_format = ""
app_title_alignment = "center"
playlist_title_alignment = "left"
metadata_title_alignment = "left"
progress_title_alignment = "left"
app_title_color = "white"
playlist_color = "white"
metadata_color = "white"
progress_color = "white"
rounded_corners = false
