[config]
toggle_playback = "space"
seek_backward = "left"
seek_forward = "right"
seek_step = 5
previous_track = "up"
next_track = "down"
quit = "q"
show_app_title = false
show_playlist_title = false
show_metadata_title = false
show_metadata_panel = false
show_progress_title = false
app_title_alignment = "center"
playlist_title_alignment = "left"
metadata_title_alignment = "left"
progress_title_alignment = "left"
rounded_corners = false
accent_color = "white"
