[config]
toggle_playback = "space"
seek_backward = "h"
seek_forward = "l"
seek_step = 5
previous_track = "k"
next_track = "j"
remove_track = "d"
reload_config = "c"
quit = "q"
show_app_title = true
show_playlist_title = true
show_metadata_title = true
show_metadata_panel = true
show_progress_title = false
app_title_format = "┤ Sonido v{VERSION} ├"
playlist_title_format = "┤ Playlist ├"
metadata_title_format = "┤ Metadata ├"
progress_title_format = "┤ Progress ├"
app_title_alignment = "center"
playlist_title_alignment = "left"
metadata_title_alignment = "left"
progress_title_alignment = "left"
rounded_corners = false
accent_color = "green"
